### ISSUE TITLE
The od-broker may run into "too many open files" issue when the network connectivity between broker and (bosh or API server) is broken or has high latency

### ISSUE THREAD

**Issue by ahrtr** [pivotal-cf/on-demand-service-broker#107]
There is a customer issue: https://pivotal-spike.atlassian.net/browse/PKS-822 

I am pretty sure the root cause is coming from on-demand-service-broker, please refer to my analysis below,
https://confluence.eng.vmware.com/pages/viewpage.action?pageId=735807705 

Please keep this in mind: **never occupy a lock during time-consuming network communication or I/O**

**Currently design & implementation**
Actually this is a generic issue, all operations supported by od-broker are serial operations, even for different clusters. It’s definitely not good.

Provision/Deprovision/Update/Upgrade operations share the same lock. When a user is executing a command creating or deleting or upgrading or updating a cluster, then he/she can't execute another command creating or deleting or updating or upgrading a different cluster before the previous command returns. If a user issues two or more commands at the same time, they will be executed one by one.

Bind (pks get-credentials xxx) operations share a different lock. When a user is executing a “pks get-credentials ”, then he/she can’t execute another “pks get-credentials ” command on a different cluster before the previous one returns.

Normally when the network connectivity is good, then this is not a big issue. But when the network between od-broker and (bosh or api-server) is down or has big latency, then the users may run into the issue described in this ticket.

**The solution**

Users can execute commands (Provision/Deprovision/Update/Upgrade/Bind) against different clusters in parallel;

Commands on the same cluster will be executed one by one. When the od-broker is processing a request for a cluster, If od-broker receives a new request on the same cluster, then it will return an error indicating it’s busy right now, and the user may try again later.

**Comment by FelisiaM** [comment]
Hi @ahrtr 

At the moment we are trying to keep changes to ODB at a minimum and just address critical issues.
Given that I will close this issue.

Please let us know if you want to reopen it.

Thanks,
Felisia
