### ISSUE TITLE
upgrade-all-service-instances with service-instances-api , missing a disable_ssl_cert_verification option

### ISSUE THREAD

**Issue by PhilippeKhalife** [pivotal-cf/on-demand-service-broker#14]
I am using the service-instances-api to gain control over what and when service instances get upgraded.

The service-instances-api end point implementation is a CF hosted application.  In test environment, there are cases when we can't get to the  root_ca_cert and it would be of useful to have 
"disable_ssl_cert_verification" .  Just as it is available for other odb configuration ( broker, cf, .. )

https://docs.pivotal.io/svc-sdk/odb/0-23/upgrades.html#service-instances-api

**Comment by FelisiaM** [comment]
Hello @PhilippeKhalife,

Sorry for the delay in getting back to you and thanks for submitting this and the PR.

This should be fixed now and will be available in the next version of ODB release (hopefully soon).

We're closing this issue for now

Thanks!

**Comment by PhilippeKhalife** [comment]
@FelisiaM Great to hear that, I look forward to the next release.
